[[footer]]
name = "Accueil"
url = ""
weight = 1
[[footer]]
name = "Services"
url = "about/"
weight = 2
[[footer]]
name = "Contact"
url = "contact/"
weight = 3
[[main]]
name = "Accueil"
url = ""
weight = 1
[[main]]
name = "Services"
url = "about/"
weight = 2
[[main]]
name = "Contact"
url = "contact/"
weight = 5
